cmake_minimum_required(VERSION 3.24)

project(Sand2D
    VERSION 1.0.0
    LANGUAGES C CXX
)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
endif()

option(SANDBOX_WARNINGS_AS_ERRORS "Treat warnings as errors" OFF)
option(SANDBOX_ENABLE_ASAN "Enable AddressSanitizer" OFF)

add_subdirectory(src)
